spring:
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
  profiles:
    active: pro
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    favicon:
      enabled: true


comment.avatar: /img/微信图片_20230815223846.jpg